name: Test the ruby generator

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ruby-generator-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        path: shared-slides
    - uses: actions/checkout@v3.1.0
      with:
        repository: DanySK/Course-DTM-SE-3
        path: target
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.117.0
      with:
        working-directory: shared-slides
    - name: Run tests
      run: |
        ruby -c shared-slides/preprocess.rb
        shared-slides/preprocess.rb
        [ -s target/content/dvcs-basics/_index.md ]
